### PR TITLE
authenticode: reduce memory allocations

### PR DESCRIPTION
**Pull request by DmitriyMV**
This PR does those things:
- If we know that `io.ReaderAt` also implements `io.Seeker` we can calculate the whole size, those avoiding unnecessary reallocations during buffer growth.
- Sort using generics based `slices.SortFunc` instead of reflection-lite based `sort.Slice`.
- Read section data directly into the buffer, without allocating new slice.
- Read entire file content into the `io.Discard` since this variable is never used or mentioned again.
- Add `PECOFFBinary.Open` which allows users to stream binary data rather than getting a new intermediate slice.

In our project (Talos OS) this changes allowed us to reduce memory usage from 1.6 GiB down to 600 MiB

### CODE REVIEW

**Comment by Foxboron** [comment]
Right, I had an assumption the new implementation was a bit too clever.

It would be nice with a couple of test cases where we hard code the expected checksums from the old implementations to ensure we are not changing anything.

**Comment by DmitriyMV** [comment]
@Foxboron can you point me to the right direction? My PE skills are a bit rusty here 😅

**Comment by DmitriyMV** [comment]
@Foxboron I added missing check in `TestSignVerify` and updated test a bit, but it looks like expected checksums are covered using the old tests.

**Review by Foxboron — APPROVED** [review]

**Comment by DmitriyMV** [comment]
@Foxboron waiting for your merge then, cause we are planning to introduce this into the Talos as soon as we can

**Comment by Foxboron** [comment]
@DmitriyMV I'll merge it after work probably.

**Comment by Foxboron** [comment]
Thanks!

**Comment by DmitriyMV** [comment]
🎉

**Pull request merged**
